spec:
  template:
    spec:
      containers:
        - name: mood-service
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10