apiVersion: apps/v1
kind: Deployment
metadata:
  name: mood-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
        - name: mood-service
          image: mood-service:1.0.0
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 800m
              memory: 1Gi
          env:
            - name: spring.redis.host
              value: "mood-redis"
            - name: mood_not_found_message
              value: "default for Kubernetes"
---
apiVersion: v1
kind: Service
metadata:
  name: mood-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: service
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mood-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: mood-redis
          image: redis:6.0.3-alpine
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: mood-redis
  namespace: default
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379